os: linux
dist: xenial
language: node_js
script:
  - yarn build
deploy:
  strategy: git
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
